name: neurodocs-ai

services:
  document-api:
    build:
      context: ./services/document-api
    container_name: neurodocs-document-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - neurodocs

  web:
    build:
      context: ./apps/web
    container_name: neurodocs-web
    ports:
      - "4200:4200"
    depends_on:
      - document-api
    networks:
      - neurodocs

networks:
  neurodocs:
    driver: bridge
